# Priority decreases going downward ie. If two regexes match the same piece of
# text, the one defined earlier will take precedence over the one defined later.
# Headings
'##?#?#?#?#?.*': MAGENTA

# Code blocks
'```(.|\n)+?```': YELLOW

# Bold text
'\b__[^_]+?__\b': BOLD_WHITE

# Italic text
'\b_[^_]+?_\b': ITALIC_WHITE
